Repository UniqueTMT/Unique, pull requests merged in 2025-04, with the labels that each got.

#14 [feat] #13 room, exam entity 및 일부 DTO 수정
  src/main/java/com/unique/controller/RoomRestController.java
  src/main/java/com/unique/dto/ExamDTO.java
  src/main/java/com/unique/dto/RoomDTO.java
  src/main/java/com/unique/entity/AppealEntity.java
  src/main/java/com/unique/entity/ExamEntity.java
  src/main/java/com/unique/entity/MemberLogEntity.java
  src/main/java/com/unique/entity/RoomEntity.java
  src/main/java/com/unique/repository/AnswerRepository.java
  src/main/java/com/unique/repository/ExamRepository.java
  src/main/java/com/unique/repository/RoomRepository.java
  src/main/java/com/unique/service/AnswerServiceImpl.java
  src/main/java/com/unique/service/ExamService.java
  src/main/java/com/unique/service/ExamServiceImpl.java
  src/main/java/com/unique/service/RoomService.java
  src/main/java/com/unique/service/RoomServiceImpl.java
Labels: feat ✨

#16 [hotfix] #15 hotfix 관계선 재정의
  src/main/java/com/unique/controller/AnswerRestController.java
  src/main/java/com/unique/entity/AnswerEntity.java
  src/main/java/com/unique/entity/AppealEntity.java
  src/main/java/com/unique/entity/ApplysEntity.java
  src/main/java/com/unique/entity/ExamEntity.java
  src/main/java/com/unique/entity/QuizEntity.java
  src/main/java/com/unique/entity/RoomEntity.java
  src/main/java/com/unique/service/AnswerService.java
  src/main/java/com/unique/service/AnswerServiceImpl.java
  src/main/java/com/unique/service/RoomServiceImpl.java
  src/main/resources/application.properties
Labels: hotfix 🚨

#22 [add] #19 add dto 작성
  src/main/java/com/unique/controller/ExamParticipationController.java
  src/main/java/com/unique/dto/ExamDTO.java
  src/main/java/com/unique/dto/ExamParticipationDTO.java
  src/main/java/com/unique/repository/ExamParticipationRepository.java
  src/main/java/com/unique/service/ExamParticipationService.java
  src/main/java/com/unique/service/ExamParticipationServiceImpl.java
Labels: add ➕

#24 [add]/#12 add dto 작성
  src/main/java/com/unique/dto/AppealDTO.java
  src/main/java/com/unique/dto/MemberInfoDTO.java
  src/main/java/com/unique/dto/RoomDTO.java
  src/main/java/com/unique/dto/UserExamHistoryDTO.java
  src/main/java/com/unique/dto/UserExamHistoryDetailDTO.java
  src/main/resources/application.properties
Labels: add ➕

#29 [mod] 시험방 생성 수정
  src/main/java/com/unique/config/WebConfig.java
  src/main/java/com/unique/controller/RoomRestController.java
  src/main/java/com/unique/dto/ExamDTO.java
  src/main/java/com/unique/dto/RoomDTO.java
  src/main/java/com/unique/repository/RoomRepository.java
  src/main/java/com/unique/service/RoomService.java
  src/main/java/com/unique/service/RoomServiceImpl.java
Labels: mod 〰

#30 [feat] dto 동작 확인
  src/main/java/com/unique/controller/ApplysRestController.java
  src/main/java/com/unique/dto/UserExamHistoryDTO.java
  src/main/java/com/unique/dto/UserExamHistoryDetailDTO.java
  src/main/java/com/unique/repository/ApplysRepository.java
  src/main/java/com/unique/service/ApplysService.java
  src/main/java/com/unique/service/ApplysServiceImpl.java
Labels: feat ✨

#32 [feat] #21 feat 전반적인 dto 수정
  src/main/java/com/unique/config/ModelMapperConfig.java
  src/main/java/com/unique/controller/AnswerRestController.java
  src/main/java/com/unique/controller/AppealRestController.java
  src/main/java/com/unique/controller/ApplysRestController.java
  src/main/java/com/unique/controller/ExamRestController.java
  src/main/java/com/unique/controller/MemberLogRestController.java
  src/main/java/com/unique/controller/MemberRestController.java
  src/main/java/com/unique/controller/RoomRestController.java
  src/main/java/com/unique/dto/AnswerDTO.java
  src/main/java/com/unique/dto/AnswerDetailDTO.java
  src/main/java/com/unique/dto/ExamDTO.java
  src/main/java/com/unique/dto/ExamDetailDTO.java
  src/main/java/com/unique/dto/QuizSummaryDTO.java
  src/main/java/com/unique/dto/RoomDTO.java
  src/main/java/com/unique/repository/AnswerRepository.java
  src/main/java/com/unique/repository/ExamRepository.java
  src/main/java/com/unique/repository/RoomRepository.java
  src/main/java/com/unique/service/AnswerService.java
  src/main/java/com/unique/service/AnswerServiceImpl.java
  src/main/java/com/unique/service/ExamService.java
  src/main/java/com/unique/service/ExamServiceImpl.java
  src/main/java/com/unique/service/RoomService.java
  src/main/java/com/unique/service/RoomServiceImpl.java
Labels: feat ✨

#34 [feat] #31 동작 확인
  src/main/java/com/unique/controller/ApplysRestController.java
  src/main/java/com/unique/controller/MemberController.java
  src/main/java/com/unique/controller/MemberRestController.java
  src/main/java/com/unique/dto/MemberInfoDTO.java
  src/main/java/com/unique/dto/UserExamHistoryDetailDTO.java
  src/main/java/com/unique/repository/MemberRepository.java
  src/main/java/com/unique/repository/UserExamHistoryDetailRepository.java
  src/main/java/com/unique/service/MemberService.java
  src/main/java/com/unique/service/MemberServiceImpl.java
  src/main/java/com/unique/service/UserExamHistoryDetailServiceImpl.java
Labels: feat ✨

#36 [feat] #33 feat controller 테스트
  src/main/java/com/unique/controller/AnswerRestController.java
  src/main/java/com/unique/controller/ApplysRestController.java
  src/main/java/com/unique/dto/ExamDTO.java
  src/main/java/com/unique/repository/RoomRepository.java
  src/main/java/com/unique/service/RoomServiceImpl.java
Labels: feat ✨

#38 [add] DTO 작성
  src/main/java/com/unique/controller/admin/AdminController.java
  src/main/java/com/unique/dto/admin/AdminExamMonthlyStatsDTO.java
  src/main/java/com/unique/dto/admin/AdminExamStatsDTO.java
  src/main/java/com/unique/dto/admin/AdminRecentExamDTO.java
  src/main/java/com/unique/dto/admin/AdminRoomCountDTO.java
  src/main/java/com/unique/dto/admin/AdminRoomDTO.java
  src/main/java/com/unique/dto/admin/AdminUserLogDTO.java
  src/main/java/com/unique/repository/MemberLogRepository.java
  src/main/java/com/unique/repository/admin/AdminRepository.java
  src/main/java/com/unique/service/MemberLogService.java
  src/main/java/com/unique/service/MemberLogServiceImpl.java
  src/main/java/com/unique/service/admin/AdminService.java
  src/main/java/com/unique/service/admin/AdminServiceImpl.java
Labels: add ➕

#42 Feat/#40 feat 화면 흐름 초기 설정
  src/main/java/com/unique/controller/MemberController.java
  src/main/java/com/unique/controller/MemberLogRestController.java
  src/main/java/com/unique/controller/MemberRestController.java
  src/main/java/com/unique/dto/member/FindIdRequestDTO.java
  src/main/java/com/unique/dto/member/FindPwRequestDTO.java
  src/main/java/com/unique/dto/member/LoginRequestDTO.java
Labels: add ➕

#44 [feat] #37 시험생성 controller 개발
  .gitignore
  src/main/java/com/unique/controller/AnswerRestController.java
  src/main/java/com/unique/controller/ApplysRestController.java
  src/main/java/com/unique/controller/ExamRestController.java
  src/main/java/com/unique/controller/MemberRestController.java
  src/main/java/com/unique/controller/QuizRestController.java
  src/main/java/com/unique/controller/RoomRestController.java
  src/main/java/com/unique/dto/AnswerDTO.java
  src/main/java/com/unique/gpt/GPTClient.java
  src/main/java/com/unique/gpt/GptQuestionController.java
  src/main/java/com/unique/gpt/GptTestController.java
  src/main/java/com/unique/gpt/QuizParser.java
  src/main/java/com/unique/repository/AnswerRepository.java
  src/main/java/com/unique/repository/QuizRepository.java
  src/main/java/com/unique/service/AnswerService.java
  src/main/java/com/unique/service/AnswerServiceImpl.java
  src/main/java/com/unique/service/QuizService.java
  src/main/java/com/unique/service/QuizServiceImpl.java
  src/main/java/com/unique/service/RoomService.java
  src/main/java/com/unique/service/RoomServiceImpl.java
  src/main/java/com/unique/service/UserExamHistoryDetailServiceImpl.java
  src/main/resources/application.properties
Labels: feat ✨

#50 [feat] gpt문제생성 하드코딩으로 확인
  src/main/java/com/unique/controller/ApplysRestController.java
  src/main/java/com/unique/controller/QuizRestController.java
  src/main/java/com/unique/dto/QuizDTO.java
  src/main/java/com/unique/gpt/GPTClient.java
  src/main/java/com/unique/gpt/GptTestController.java
Labels: feat ✨

#56 [feat] 오답 노트 세부 출력
  src/main/java/com/unique/controller/appeal/AppealRestController.java
  src/main/java/com/unique/controller/applys/ApplysRestController.java
  src/main/java/com/unique/dto/member/MemberExamHistoryDTO.java
  src/main/java/com/unique/dto/member/MemberExamHistoryDetailDTO.java
  src/main/java/com/unique/impl/appeal/AppealServiceImpl.java
  src/main/java/com/unique/impl/applys/ApplysServiceImpl.java
  src/main/java/com/unique/impl/member/MemberExamHistoryDetailServiceImpl.java
  src/main/java/com/unique/impl/member/UserExamHistoryDetailServiceImpl.java
  src/main/java/com/unique/repository/applys/ApplysRepository.java
  src/main/java/com/unique/repository/member/MemberExamHistoryDetailRepository.java
  src/main/java/com/unique/repository/member/MemberRepository.java
  src/main/java/com/unique/service/applys/ApplysService.java
Labels: feat ✨

#63 [add] #62 Spring Security 기본구조생성완료
  src/main/java/com/unique/config/security/CustomUserDetails.java
  src/main/java/com/unique/config/security/CustomUserDetailsService.java
  src/main/java/com/unique/config/security/SecurityConfig.java
  src/main/java/com/unique/controller/member/MemberAuthController.java
Labels: add ➕

#65 [chore] #64 MemberController 삭제.
  src/main/java/com/unique/controller/member/MemberController.java
Labels: chore 🛠

#67 [feat] #58 gpt로 문제 추출 기능 개발
  .gitignore
  build.gradle
  src/main/java/com/unique/client/GptClient.java
  src/main/java/com/unique/controller/exam/ExamRestController.java
  src/main/java/com/unique/controller/gpt/GptQuestionController.java
  src/main/java/com/unique/controller/quiz/QuizRestController.java
  src/main/java/com/unique/entity/quiz/QuizEntity.java
  src/main/java/com/unique/gpt/GPTClient.java
  src/main/java/com/unique/gpt/GptQuestionController.java
  src/main/java/com/unique/gpt/QuizParser.java
  src/main/java/com/unique/impl/gpt/GptPromptServiceImpl.java
  src/main/java/com/unique/impl/gpt/GptServiceImpl.java
  src/main/java/com/unique/impl/gpt/PdfParseServiceImpl.java
  src/main/java/com/unique/impl/quiz/QuizServiceImpl.java
  src/main/java/com/unique/kafka/GptKafkaConsumer.java
  src/main/java/com/unique/kafka/GptKafkaProducer.java
  src/main/java/com/unique/repository/exam/ExamRepository.java
  src/main/java/com/unique/repository/quiz/QuizRepository.java
  src/main/java/com/unique/service/ParserService.java
  src/main/java/com/unique/service/gpt/GptPromptService.java
  src/main/java/com/unique/service/gpt/GptService.java
  src/main/java/com/unique/service/gpt/PdfParseService.java
  src/main/java/com/unique/service/quiz/QuizService.java
  src/main/resources/application.properties
Labels: feat ✨

#69 [feat] #68 힌트,배점,해설 수정 기능
  src/main/java/com/unique/controller/quiz/QuizRestController.java
  src/main/java/com/unique/dto/quiz/QuizDTO.java
  src/main/java/com/unique/impl/exam/ExamParticipationServiceImpl.java
  src/main/java/com/unique/impl/member/MemberExamHistoryDetailServiceImpl.java
  src/main/java/com/unique/impl/quiz/QuizServiceImpl.java
Labels: feat ✨

#73 Feature/#70 feat kafka 문제 생성 요청 비동기 처리
  src/main/java/com/unique/controller/gpt/GptQuestionController.java
  src/main/java/com/unique/controller/quiz/QuizRestController.java
  src/main/java/com/unique/impl/exam/ExamServiceImpl.java
  src/main/java/com/unique/kafka/GptKafkaConsumer.java
  src/main/java/com/unique/kafka/GptKafkaProducer.java
  src/main/resources/application.properties
Labels: feat ✨

#75 [feat] #74 kafka 문제 생성 요청 비동기 처리
  src/main/java/com/unique/config/KafkaProducerConfig.java
  src/main/java/com/unique/impl/gpt/GptPromptServiceImpl.java
  src/main/java/com/unique/impl/gpt/GptServiceImpl.java
  src/main/java/com/unique/kafka/GptKafkaConsumer.java
  src/main/java/com/unique/service/gpt/GptService.java
  src/main/resources/application.properties
  src/main/resources/docker-compose.yml
Labels: feat ✨

#77 [feat] #66 사용자 인증 인가 설정
  build.gradle
  src/main/java/com/unique/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/unique/config/security/CustomAuthenticationManager.java
  src/main/java/com/unique/config/security/CustomAuthenticationProvider.java
  src/main/java/com/unique/config/security/CustomLogoutSuccessHandler.java
  src/main/java/com/unique/config/security/CustomUserDetails.java
  src/main/java/com/unique/config/security/CustomUserDetailsService.java
  src/main/java/com/unique/config/security/SecurityConfig.java
  src/main/java/com/unique/config/security/SecurityConfigDevBypass.java
  src/main/java/com/unique/config/security/SecurityConfigDisable.java
  src/main/java/com/unique/controller/admin/AdminController.java
  src/main/java/com/unique/controller/admin/AdminRestController.java
  src/main/java/com/unique/controller/member/MemberAuthController.java
  src/main/java/com/unique/controller/member/MemberRestController.java
  src/main/java/com/unique/controller/security/PasswordEncodeController.java
  src/main/java/com/unique/dto/member/LoginRequestDTO.java
  src/main/java/com/unique/entity/member/MemberEntity.java
  src/main/java/com/unique/impl/admin/AdminServiceImpl.java
  src/main/java/com/unique/repository/member/MemberRepository.java
  src/main/resources/application.properties
Labels: feat ✨

#79 [feat] #76 feat 필터링 기능 개발
  src/main/java/com/unique/controller/applys/ApplysRestController.java
  src/main/java/com/unique/controller/exam/ExamRestController.java
  src/main/java/com/unique/controller/room/RoomRestController.java
  src/main/java/com/unique/dto/answer/AnswerDetailDTO.java
  src/main/java/com/unique/dto/exam/CategoryQuizCountDTO.java
  src/main/java/com/unique/impl/applys/ApplysServiceImpl.java
  src/main/java/com/unique/impl/exam/ExamServiceImpl.java
  src/main/java/com/unique/impl/gpt/GptPromptServiceImpl.java
  src/main/java/com/unique/impl/quiz/QuizServiceImpl.java
  src/main/java/com/unique/impl/room/RoomServiceImpl.java
  src/main/java/com/unique/repository/applys/ApplysRepository.java
  src/main/java/com/unique/repository/exam/ExamRepository.java
  src/main/java/com/unique/repository/room/RoomRepository.java
  src/main/java/com/unique/service/applys/ApplysService.java
  src/main/java/com/unique/service/exam/ExamService.java
  src/main/java/com/unique/service/quiz/QuizService.java
  src/main/java/com/unique/service/room/RoomService.java
Labels: feat ✨

#80 [hotfix] #78 DB 회원 비밀번호 암호화.
  src/main/java/com/unique/config/security/SecurityConfigDisable.java
Labels: hotfix 🚨

#82 [feat] #81 ID 찾기 기능 구현
  src/main/java/com/unique/controller/member/MemberRestController.java
  src/main/java/com/unique/dto/member/FindIdRequestDTO.java
  src/main/java/com/unique/impl/member/MemberServiceImpl.java
  src/main/java/com/unique/repository/member/MemberRepository.java
  src/main/java/com/unique/service/member/MemberService.java
Labels: feat ✨

#84 [feat] redis 시험 답안힌트 저장
  build.gradle
  src/main/java/com/unique/controller/appeal/AppealRestController.java
  src/main/java/com/unique/controller/applys/ApplysRestController.java
  src/main/java/com/unique/dto/appeal/AppealDTO.java
  src/main/java/com/unique/dto/appeal/AppealDetailDTO.java
  src/main/java/com/unique/dto/appeal/AppealScoreAdjustRequestDTO.java
  src/main/java/com/unique/dto/member/MemberExamHistoryDTO.java
  src/main/java/com/unique/impl/appeal/AppealServiceImpl.java
  src/main/java/com/unique/impl/applys/ApplysServiceImpl.java
  src/main/java/com/unique/impl/member/MemberExamHistoryDetailServiceImpl.java
  src/main/java/com/unique/repository/answer/AnswerRepository.java
  src/main/java/com/unique/repository/appeal/AppealRepository.java
  src/main/java/com/unique/repository/appeal/SseEmitterRepository.java
  src/main/java/com/unique/repository/applys/ApplysRepository.java
  src/main/java/com/unique/repository/member/MemberExamHistoryDetailRepository.java
  src/main/java/com/unique/service/appeal/AppealService.java
  src/main/resources/application.properties
Labels: feat ✨

#85 [feat] #83 비밀번호 찾기 구현
  build.gradle
  src/main/java/com/unique/controller/member/MemberRestController.java
  src/main/java/com/unique/dto/member/FindPwRequestDTO.java
  src/main/java/com/unique/impl/member/MemberServiceImpl.java
  src/main/java/com/unique/repository/member/MemberRepository.java
  src/main/java/com/unique/service/member/MemberService.java
  src/main/resources/application.properties
Labels: feat ✨

#91 [feat] #90 응시자 답안 상세 페이지 쿼리 추가
  src/main/java/com/unique/controller/answer/AnswerRestController.java
  src/main/java/com/unique/dto/answer/StudentExamResultDTO.java
  src/main/java/com/unique/entity/exam/ExamEntity.java
  src/main/java/com/unique/impl/answer/AnswerServiceImpl.java
  src/main/java/com/unique/repository/answer/AnswerRepository.java
  src/main/java/com/unique/repository/exam/ExamRepository.java
  src/main/java/com/unique/service/answer/AnswerService.java
Labels: feat ✨

#93 [chore] #92 controller 수정
  src/main/java/com/unique/controller/answer/AnswerRestController.java
  src/main/java/com/unique/controller/exam/ExamRestController.java
  src/main/java/com/unique/controller/gpt/GptQuestionController.java
  src/main/java/com/unique/controller/quiz/QuizRestController.java
  src/main/java/com/unique/controller/room/RoomRestController.java
  src/main/java/com/unique/service/quiz/QuizService.java
Labels: chore 🛠

#97 [mod] #96 QuizServiceImpl 수정
  src/main/java/com/unique/impl/quiz/QuizServiceImpl.java
Labels: mod 〰

#99 [mod] #98 controller 수정
  src/main/java/com/unique/controller/gpt/GptQuestionController.java
Labels: mod 〰

#100 [mod] #95 로그인 코드 수정
  src/main/java/com/unique/config/security/SecurityConfigDevBypass.java
  src/main/java/com/unique/config/security/SecurityConfigDisable.java
  src/main/java/com/unique/controller/member/MemberAuthController.java
  src/main/java/com/unique/controller/member/MemberAuthControllerOrigin.java
  src/main/java/com/unique/controller/member/MemberRestController.java
  src/main/java/com/unique/dto/member/FindIdRequestWrapper.java
  src/main/java/com/unique/dto/member/FindPwRequestWrapper.java
  src/main/java/com/unique/dto/member/LoginRequestWrapper.java
Labels: mod 〰

#102 [feat] 이의제기 기능
  src/main/java/com/unique/controller/applys/ApplysRestController.java
Labels: feat ✨

#103 Feat/#57 feat redis 시험 답안힌트 저장
  src/main/java/com/unique/config/CorsConfig.java
  src/main/java/com/unique/config/WebConfig.java
  src/main/java/com/unique/config/security/SecurityConfigDisable.java
  src/main/java/com/unique/controller/appeal/AppealRestController.java
  src/main/java/com/unique/controller/applys/ApplysRestController.java
  src/main/java/com/unique/controller/member/MemberRestController.java
  src/main/java/com/unique/dto/appeal/AppealDTO.java
  src/main/java/com/unique/impl/appeal/AppealServiceImpl.java
  src/main/java/com/unique/impl/member/MemberServiceImpl.java
  src/main/java/com/unique/repository/applys/ApplysRepository.java
  src/main/java/com/unique/service/member/MemberService.java
  src/main/resources/application.properties
Labels: feat ✨
